"""Fixing foreign key constraint

Revision ID: 723b4f43851d
Revises: f2fd2400f645
Create Date: 2023-11-21 12:56:14.296263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723b4f43851d'
down_revision: Union[str, None] = 'f2fd2400f645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spaced_repetition_user_id_fkey', 'spaced_repetition', type_='foreignkey')
    op.create_foreign_key('fk_user_id', 'spaced_repetition', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_id', 'spaced_repetition', type_='foreignkey')
    op.create_foreign_key('spaced_repetition_user_id_fkey', 'spaced_repetition', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
