"""change field words and added field for table users

Revision ID: 38c74305a11f
Revises: 52808648bbfe
Create Date: 2023-11-24 16:11:28.130724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c74305a11f'
down_revision: Union[str, None] = '52808648bbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_small', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_big', sa.String(), nullable=True))
    op.drop_column('users', 'avatar')
    op.add_column('words', sa.Column('slang', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'slang')
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_big')
    op.drop_column('users', 'avatar_small')
    # ### end Alembic commands ###
