"""change field name in table spaced_repetition

Revision ID: adb24ff2c0e4
Revises: c4989ce1249b
Create Date: 2024-01-01 14:56:35.867116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adb24ff2c0e4'
down_revision: Union[str, None] = 'c4989ce1249b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaced_repetition', sa.Column('date_repetition', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('spaced_repetition', 'date_repitition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaced_repetition', sa.Column('date_repitition', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('spaced_repetition', 'date_repetition')
    # ### end Alembic commands ###
